# Generated by Django 4.1.7 on 2023-08-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_thumbnail.jpg', upload_to='', verbose_name='썸네일'),
        ),
    ]
